### PR TITLE
fixed nasa tv streams, added ISS HD Earth Viewing Experiment, all liv…

### PR DESCRIPTION
**Pull request by weekendsource**
.

### CODE REVIEW

**Comment by bkuhls** [comment]
wfm, thx!

**Comment by jcnventura** [comment]
I can confirm this is working. Please merge the pull request!

**Comment by dersphere** [comment]
Damn I overlooked this one. Thanks for the reminder @jcnventura and thanks for the changes @weekendsource

**Comment by weekendsource** [comment]
Thank you :)

**Pull request merged**
